### ISSUE TITLE
data-가 다수키냐 단일키냐

### ISSUE THREAD

**Issue by hikaMaeng** [untiedJS/untiedJS#1]
일단 같이 토론하면서 처리해야할 중요한 주제는 data-xxx를 사용할 때 미리 정해진 이름규칙으로 쓰게 되는데 이걸 정해야한다는 거죠.
가장 깔끔한 건 아마도 data-ut="bindKey"겠죠.
대신 이렇게 되면 전체 바인딩요소가 하나의 키와 바인딩됩니다.

예를들어 이벤트, 데이터연동, 국제화 정보 등을 나누고 싶다면
data-click  data-touchstart data-i18n data-data 등의 다수키를 갖게 설계하는 것도 방법입니다.

해서 우선 각 키의 이름규칙을 정하기전에 먼저 다수키냐 단일키냐를 결정해야합니다.

중요한 포인트는 얼마나 객체와의 연결을 innerHTML을 자유롭게 해도 런타임에 빠르고 편하게 처리할 수 있고 영향도 없는가라는 관점이겠죠.

**Comment by oxizen** [comment]
단일키로 className 처럼 여러개 조합도 가능하게 하는건 어떨까 싶은 생각이 들기도 하네요;
제대로 이해나 한건지 모르겠네요.

**Comment by hikaMaeng** [comment]
http://www.bsidesoft.com/api/js/3/test/bs.html

샘플코드를 함 보면 좀 상상하는데 도움이 됨

**Comment by Hanul** [comment]
단일 키로 하면 코딩하기가 매우 불편할것으로 보입니다.
data-ut="click=func1 mousemove=func2" 이런식이 될텐데 복잡도가 매우 증가할것 같고요.
각각 나누는게 좋아보이지만 이러다 다른 library와 겹치는 문제가 생길 수 있어 그것도 그거 나름대로 고민이네요.
현실적인 대응책으로는 data-ut-click, data-ut-mousemove 등으로 ut라는 prefix를 붙히는게 방법이 될 수는 있겠습니다.

**Comment by oxizen** [comment]
class 처럼 조합한다는 것이 예를들면 data-ut='grocery draggable' 처럼 하는건 어떨까 싶어서요 각 리스너 대응은 js쪽에서 하고요. 구체적으로 함수를 명시하는거 보다는 좀더 유연하지 않을까 싶습니다.

**Comment by hikaMaeng** [comment]
유연함은 곧 복잡함의 동의어라는게 문제이긴 한데 ㅎㅎ
일단 이벤트만큼의 키가 있으면 이벤트 리스너에서 그 키만 검사하면 되지만 아니라면 알단 무조건 카를 얻어서 파싱해서 객체대조를 해야함.

이 부하는 단순히 로직이 더 처리되는 부하가 아니라 dom통신을 줄일수있냐와 직결되는 문제이긴한데 ㅎㅎ

**Comment by oxizen** [comment]
샘플코드 던지신 수준으로 single키도 큰 문제는 없어 보였는데, 그렇게 했을때 대동소이한 다른 키가 생성되야할 상황에 대한 부분에 대해서 고민하다가 클래스랑 비슷하게 운용하는걸 생각해 봤습니다. 키파싱 후 매칭되는 object쪽에 키를 탐색하는 비용이 있긴하겠지만.. 이게 dom통신 이슈인건가요 흐흐.

**Comment by redcamel** [comment]
먼가 앵귤러스러운 -0-

**Comment by Hanul** [comment]
고민해보니 data-click data-touchstart 등의 이벤트의 이름을 가진 data를 지정할까 싶기도 합니다.
untiedJS와 같은 기능을 가진 다른 코드가 존재한다면 untiedJS를 사용하지 않을테니까요.
그리고 개인적으로 스펙이 변경되는 사항에 대해서는 반대합니다. 사람마다 장단점에 대한 생각은 주관적인 것이고, 그러다 보면 저희가 모를수도 있는 다른 라이브러리에서 구현된 스펙의 방향과 비슷하게 발전할 여지가 있어서요. 저는 장단점을 떠나서 untiedJS 고유의 특별한 점을 가졌으면 좋겠습니다. :)

**Comment by redcamel** [comment]
<div data-down="a" data-up="a" data-move="a" data-data="a" data-i18n="a" data-vali="a"></div>
<div data-ut="down:a up:a move:a data:a data:i18n:a vali:a"></div>
단순 정의라는 측면에서 봤을때 단일키가 좀더 좋아보이긴한데..

**Comment by hikaMaeng** [comment]
선기 인바이트 이메일로 보냈음.
단일키와 아닌 경우 js데이터와 연동되는 과정을 이벤트리스너에서의 코드로 보면

여러키인 경우
function(e){
   if(v = data[e.target.getAttribute('data-' + e.type)]){  ...
}
정도에서 얻어지고 단일키는
function parseData(el){
   v = el.getAttribute('data-ut');
   if(!v)return;
   v = v.split(' '), i = v.length;
   while(i--) v[i] = v.split(':'), v[v[i][0]] = v[v[i][1]];
   return v;
}

function(e){
    v = parseData(e.target);
    if(v && v[e.type]){.....
}
이렇게 되어 반드시 함수를 한번더 거치고
parser에서 객체생성을 아무리 억제해도 이 정도..

그럼 이정도가 부하가 되냐라고 물어보면 onscroll과 onresize, onmove는 초당 ㄷㄷㄷ불러댐..
최적화를 잘안하지만 언제나 강조하듯 프레임단위로 호출되는 애들은 반드시 해야하기 때문에..
그게 바로 단일키를 쓸때 가장 고민되는 부분인 것임..

**Comment by Hanul** [comment]
근데 여러키라도 onscroll, onresize같은건 최적화가 필수겠습니다.

**Comment by hikaMaeng** [comment]
좀 빡빡하긴 한데 이벤트별로 주저리다는 것도 문제가 있어보여 개안적으로는
<div data-event="touchstart:a b c, touchend:b"/> 정도로 이벤트난 묶는 레벨이 어떨까 생각하고 있습니다.

리스너내의 구현코드도

if(v = target.getAttribute("data-event")){
...

라는 식으로 타겟을 스캅할지 말지를 판단하는데 큰 비용이 안들고 일단 if안에 들어와서는 js 문자열 평가라서 좀 파싱비용이 들어도 할만하다는 생각입니다.

**Comment by hikaMaeng** [comment]
태그가 모바일에서 작성하면 날아감
data-event="click:a b c, touchstart:a"

**Comment by Hanul** [comment]
코드가 복잡해보여서 저는 반대입니다. 이벤트별로 다는게 길어지긴 하지만 깔끔한것같습니다.

**Comment by oxizen** [comment]
혹시 메일에 답글을 달면 댓글이 달리는건가요..

2015년 12월 1일 오전 12:39, Young Jae Sim <notifications@github.com>님이 작성:

**Comment by Hanul** [comment]
@oxizen 네 달립니다. 첨 알았어요!

**Comment by hikaMaeng** [comment]
그러니까 이 이슈의 결론은...다수키인가단일키인가...역시 투표로 고~

**Comment by hanmomhanda** [comment]
이 글들 마크다운 적용됩니당. 꺽쇠 쓰는 코드는 키보드 좌상귀에 있는 `<div>`으로` 감싸주면 나와용

**Comment by Hanul** [comment]
예제 작성합니다.
- 이벤트, 데이터 등 큰 덩어리
```
<dom data-ut-event="click:a, mouseover:b" data-ut-data="...">
```
- 개별이벤트, 기능키 별로 따로
```
<dom data-ut-click="a" data-ut-mouseover="b">
```
- `data-ut` 단일
```
<dom data-ut="event: {click:a, mouseover:b}">
```

**Comment by hikaMaeng** [comment]
이건은 개별이벤트 별로 키를 부여하는 것으로 마감되었습니다.
https://www.facebook.com/groups/untiedJS/permalink/1701084320102953/
