### ISSUE TITLE
stopPropagation 처리

### ISSUE THREAD

**Issue by hikaMaeng** [untiedJS/untiedJS#10]
짜피 bubble과정에서 body는 가장 마지막에 이벤트를 수신하게 됩니다.
해서 큰 의미는 없지만 기본적으로 doc용 이벤트리스너에 stopPoropagation을 할 수 있게 해주려는 것입니다.

```javascript
document.onclick = function(e){
    e.stopPropagation();
    //...실제할일
};

**Comment by Hanul** [comment]
side effect가 없다면 굳이 넣지 않아도 괜찮을것 같습니다.

**Comment by hikaMaeng** [comment]
그냥 안하는걸로 ^^
