### ISSUE TITLE
이벤트 전파와 가드의 개념

### ISSUE THREAD

**Issue by hikaMaeng** [untiedJS/untiedJS#3]
dom에서 버블링 이벤트는 자동으로 전파되지만 위임한 경우 e.target이 data-xxx를 안 갖고 있으면 거기서 멈춰버립니다.

이것을 개선하여 
do{
  if(target.getAttr(...)){
     ....
     break;
  }
}while(target = target.parentNode)

형태로 개선하면 버블링을 타고 가는 효과가 생깁니다.
하지만 이렇개 하면 상당한 뎁스에 있는 엘리먼트가 body까지 항상 탐색하는 결과를 낳게 되어 이벤트가 걸려있는 공간에서는 금방 버블링으로 대상을 찾지만 이벤트가 안걸린 빈 공간을 클릭하면 항상 body까지 찾는 비효율과 속도 저하를 가져옵니다.
이를 보완하기 위해 레이어 중간중간 버블링 가드를 두는 방법을 생각해볼 수 있습니다.

div
  div data-stop
     div
         div data-event

위의 구조에서는 빈공간을 눌러도 data-stop(가칭)까지만 전진하고 그 이후는 버블링 탐색을 그만두게 할 수 있습니다. 아까의 루프는 다음과 같아 지겠죠.

}while(target = target.parentNode && !target.getAttribute("data-stop"))

이러한 버블랑 스토퍼의 도입과 이름키에 대해 토론해보죠.

**Comment by Hanul** [comment]
이벤트 버블링을 지원...해야겠죠?

**Comment by oxizen** [comment]
실제 e.target이 이벤트를 소비할 녀석의 자식이 될 가능성도 높기때문에 버블링은 반드시 해야 될 것 같긴 한데요.. 캡쳐단계에서 막을수 있으면 참 좋겠지만.. 방법이 없겠죠.. 이런 무의미한 의견이라니;

**Comment by oxizen** [comment]
data-event 쪽에서 계속 버블링 할지 여부를 판단하는건 어떨까요.

**Comment by hikaMaeng** [comment]
그 키에서 버블링하지말지는 일단 그넘에게 닿아야함 ^^
지금 그넘에게 닿게할거나 아니냐를 만드는중이니까 ㅎㅎ

캡쳐링을 허용할 레벨이면 ie를 버리자는 레벨이라서 받아들이기 힘들고 move는 캡쳐가 막으면 네이티브스크롤이 막히니 안됨

**Comment by Hanul** [comment]
data-stop은 흔하게 쓰일 수 있을것 같습니다. 아무래도 prefix를 붙히는 방향을 고려하지 않을수가 없네요. data-ut-stop과 같은 방식은 어떨까요?

**Comment by oxizen** [comment]
아 그렇죠.. 무위로 사라질 수많은 이벤트따위는 생각도 안했네요 ㅋㅋㅋ 역시 직접 만들지 않고서는 겉핥기네요 흐

**Comment by hikaMaeng** [comment]
아직 등장하지 않은 group의 개념이 있는데 group자체가 가드가 되게 할까라는 생각도 하는중입니다 ^^;
암튼 일단 이건은 가드는 도입한다정도에서 마감하겠습니다.
