### ISSUE TITLE
Indentation convention

### ISSUE THREAD

**Issue by imazine** [untiedJS/untiedJS#6]
거창하게 code convention 까지는 아니더라도 indentation 을 2-space로 할지 4-space로 할지는 정해야 할 것 같습니다. 댓글로 의견을 수렴하여 금일중에 반영하는 것이 어떨까 합니다.

**Comment by fabulousu** [comment]
2-space 한표요. 깃헙에도 poll 기능이 있으면 좋겠군요

**Comment by Hanul** [comment]
저는 1탭이요 :)

**Comment by imazine** [comment]
1탭의 경우 지원하는 에디터에 따라 다르게 표시가 되고 실제 CLI를 많이 사용하는 사람들에게는 틀어져 보일 수 있는 문제가 있어서 space를 많이 쓰는 추세입니다. ^^ 모두의 에디터가 하나가 아니니까요

**Comment by Hanul** [comment]
@imazine 맞는 말씀이십니다. 저는 뭘 쓰든 상관없긴한데 페북 투표에 의하면 탭을 원하시는 분들이 많으세요. 아마 국내에는 Java 기반 플젝 하시는 분들이 많아서 탭이 익숙한것이 아닐까 생각해봅니다.

**Comment by imazine** [comment]
@Hanul 저도 딱히 가리지는 않지만 요즘 2-space나 4-space를 많이 사용하다 보니 tab보다는 장점이 많은 것 같아서 적어보았습니다.... 결국 대세를 따라야 겠지요 :smiley:

**Comment by hikaMaeng** [comment]
이 이슈는 탭으로 마감되었습니다.
https://www.facebook.com/groups/untiedJS/permalink/1700895890121796/

**Comment by imazine** [comment]
:+1:

**Comment by fabulousu** [comment]
1탭은 space 4간격인가요?

Outlook에서 보냄
